---
version: 1
disable_existing_loggers: false
formatters:
  normal:
    format: "[%(asctime)s %(process)d %(thread)d %(filename)s:%(lineno)s %(name)s %(levelname)s] - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: normal
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: normal
    filename: "service.log.bz2"
    when: D
    backupCount: 7
    encoding: utf-8
    utc: true
root:
  level: DEBUG
  handlers:
  - console
  - file_handler
